import { parsePhoneNumber } from "npm:awesome-phonenumber";

const ituCountries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "DPR Korea",
  "DR Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao P.D.R.",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkmenistan",
  "Tuvalu",
  "Türkiye",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Viet Nam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

export type ITUCountry = typeof ituCountries[number];

export function isITUCountry(country: unknown): country is ITUCountry {
  return !!country && ituCountries.includes(country as ITUCountry);
}

const ituCountryCodes = [
  "AFG",
  "ALB",
  "ALG",
  "AND",
  "AGL",
  "ATG",
  "ARG",
  "ARM",
  "AUS",
  "AUT",
  "AZE",
  "BAH",
  "BHR",
  "BGD",
  "BRB",
  "BLR",
  "BEL",
  "BLZ",
  "BEN",
  "BTN",
  "BOL",
  "BIH",
  "BOT",
  "B",
  "BRU",
  "BUL",
  "BFA",
  "BDI",
  "CPV",
  "CBG",
  "CME",
  "CAN",
  "CAF",
  "TCD",
  "CHL",
  "CHN",
  "CLM",
  "COM",
  "COG",
  "CTR",
  "CTI",
  "HRV",
  "CUB",
  "CYP",
  "CZE",
  "KRE",
  "COD",
  "DNK",
  "DJI",
  "DMA",
  "DOM",
  "EQA",
  "EGY",
  "SLV",
  "GNE",
  "ERI",
  "EST",
  "SWZ",
  "ETH",
  "FJI",
  "FIN",
  "F",
  "GAB",
  "GMB",
  "GEO",
  "D",
  "GHA",
  "GRC",
  "GRD",
  "GTM",
  "GUI",
  "GNB",
  "GUY",
  "HTI",
  "HND",
  "HNG",
  "ISL",
  "IND",
  "INS",
  "IRN",
  "IRQ",
  "IRL",
  "ISR",
  "I",
  "JMC",
  "J",
  "JOR",
  "KAZ",
  "KEN",
  "KIR",
  "KOR",
  "KWT",
  "KGZ",
  "LAO",
  "LVA",
  "LBN",
  "LSO",
  "LBR",
  "LBY",
  "LIE",
  "LTU",
  "LUX",
  "MDG",
  "MWI",
  "MLA",
  "MLD",
  "MLI",
  "MLT",
  "MHL",
  "MTN",
  "MAU",
  "MEX",
  "FSM",
  "MDA",
  "MCO",
  "MNG",
  "MNE",
  "MRC",
  "MOZ",
  "BRM",
  "NMB",
  "NRU",
  "NPL",
  "HOL",
  "NZL",
  "NCG",
  "NGR",
  "NIG",
  "MKD",
  "NOR",
  "OMA",
  "PAK",
  "PNR",
  "PNG",
  "PRG",
  "PRU",
  "PHL",
  "POL",
  "POR",
  "QAT",
  "ROU",
  "RUS",
  "RRW",
  "KNA",
  "LCA",
  "VCT",
  "SMO",
  "SMR",
  "STP",
  "ARS",
  "SEN",
  "SRB",
  "SEY",
  "SRL",
  "SNG",
  "SVK",
  "SVN",
  "SLM",
  "SOM",
  "AFS",
  "SSD",
  "E",
  "CLN",
  "SDN",
  "SUR",
  "S",
  "SUI",
  "SYR",
  "TJK",
  "TZA",
  "THA",
  "TLS",
  "TGO",
  "TON",
  "TRD",
  "TUN",
  "TKM",
  "TUV",
  "TUR",
  "UGA",
  "UKR",
  "UAE",
  "G",
  "USA",
  "URG",
  "UZB",
  "VUT",
  "CVA",
  "VEN",
  "VTN",
  "YEM",
  "ZMB",
  "ZWE",
] as const;

export type ITUCountryCode = typeof ituCountryCodes[number];

export function isITUCountryCode(
  countryCode: unknown,
): countryCode is ITUCountryCode {
  return !!countryCode &&
    ituCountryCodes.includes(countryCode as ITUCountryCode);
}

const ituDomains = [
  "AF",
  "AL",
  "DZ",
  "AD",
  "AO",
  "AG",
  "AR",
  "AM",
  "AU",
  "AT",
  "AZ",
  "BS",
  "BH",
  "BD",
  "BB",
  "BY",
  "BE",
  "BZ",
  "BJ",
  "BT",
  "BO",
  "BA",
  "BW",
  "BR",
  "BN",
  "BG",
  "BF",
  "BI",
  "CV",
  "KH",
  "CM",
  "CA",
  "CF",
  "TD",
  "CL",
  "CN",
  "CO",
  "KM",
  "CG",
  "CR",
  "CI",
  "HR",
  "CU",
  "CY",
  "CZ",
  "KP",
  "CD",
  "DK",
  "DJ",
  "DM",
  "DO",
  "EC",
  "EG",
  "SV",
  "GQ",
  "ER",
  "EE",
  "SZ",
  "ET",
  "FJ",
  "FI",
  "FR",
  "GA",
  "GM",
  "GE",
  "DE",
  "GH",
  "GR",
  "GD",
  "GT",
  "GN",
  "GW",
  "GY",
  "HT",
  "HN",
  "HU",
  "IS",
  "IN",
  "ID",
  "IR",
  "IQ",
  "IE",
  "IL",
  "IT",
  "JM",
  "JP",
  "JO",
  "KZ",
  "KE",
  "KI",
  "KR",
  "KW",
  "KG",
  "LA",
  "LV",
  "LB",
  "LS",
  "LR",
  "LY",
  "LI",
  "LT",
  "LU",
  "MG",
  "MW",
  "MY",
  "MV",
  "ML",
  "MT",
  "MH",
  "MR",
  "MU",
  "MX",
  "FM",
  "MD",
  "MC",
  "MN",
  "ME",
  "MA",
  "MZ",
  "MM",
  "NA",
  "NR",
  "NP",
  "NL",
  "NZ",
  "NI",
  "NE",
  "NG",
  "MK",
  "NO",
  "OM",
  "PK",
  "PA",
  "PG",
  "PY",
  "PE",
  "PH",
  "PL",
  "PT",
  "QA",
  "RO",
  "RU",
  "RW",
  "KN",
  "LC",
  "VC",
  "WS",
  "SM",
  "ST",
  "SA",
  "SN",
  "RS",
  "SC",
  "SL",
  "SG",
  "SK",
  "SI",
  "SB",
  "SO",
  "ZA",
  "SS",
  "ES",
  "LK",
  "SD",
  "SR",
  "SE",
  "CH",
  "SY",
  "TJ",
  "TZ",
  "TH",
  "TL",
  "TG",
  "TO",
  "TT",
  "TN",
  "TM",
  "TV",
  "TR",
  "UG",
  "UA",
  "AE",
  "GB",
  "US",
  "UY",
  "UZ",
  "VU",
  "VA",
  "VE",
  "VN",
  "YE",
  "ZM",
  "ZW",
] as const;

export type ITUDomain = typeof ituDomains[number];

export function isITUDomain(domain: unknown): domain is ITUDomain {
  return !!domain && ituDomains.includes(domain as ITUDomain);
}

export function parseITUDomain(
  phonenumber: string,
  verified = false,
): ITUDomain | undefined {
  const { regionCode } = parsePhoneNumber(toE164(phonenumber));
  if (!verified || isITUDomain(regionCode)) {
    return regionCode as ITUDomain;
  }
  return undefined;
}

export function toE164(phonenumber: string) {
  if (phonenumber.startsWith("+") || phonenumber.startsWith("0")) {
    return phonenumber;
  }
  return `+${phonenumber}`;
}

const ituLanguages = [
  "AR",
  "CN",
  "EN",
  "ES",
  "FR",
  "RU",
] as const;

export type ITULanguage = typeof ituLanguages[number];

export function isITULanguage(language: unknown): language is ITULanguage {
  return !!language && ituLanguages.includes(language as ITULanguage);
}

export interface ITUMember {
  country: ITUCountry;
  countryCode: ITUCountryCode;
  domain: ITUDomain;
  language: ITULanguage;
}

export const ITU_MEMBERS: ITUMember[] = [
  { country: "Afghanistan", countryCode: "AFG", domain: "AF", language: "EN" },
  { country: "Albania", countryCode: "ALB", domain: "AL", language: "EN" },
  { country: "Algeria", countryCode: "ALG", domain: "DZ", language: "AR" },
  { country: "Andorra", countryCode: "AND", domain: "AD", language: "FR" },
  { country: "Angola", countryCode: "AGL", domain: "AO", language: "EN" },
  {
    country: "Antigua and Barbuda",
    countryCode: "ATG",
    domain: "AG",
    language: "EN",
  },
  { country: "Argentina", countryCode: "ARG", domain: "AR", language: "ES" },
  { country: "Armenia", countryCode: "ARM", domain: "AM", language: "EN" },
  { country: "Australia", countryCode: "AUS", domain: "AU", language: "EN" },
  { country: "Austria", countryCode: "AUT", domain: "AT", language: "EN" },
  { country: "Azerbaijan", countryCode: "AZE", domain: "AZ", language: "RU" },
  { country: "Bahamas", countryCode: "BAH", domain: "BS", language: "EN" },
  { country: "Bahrain", countryCode: "BHR", domain: "BH", language: "AR" },
  { country: "Bangladesh", countryCode: "BGD", domain: "BD", language: "EN" },
  { country: "Barbados", countryCode: "BRB", domain: "BB", language: "EN" },
  { country: "Belarus", countryCode: "BLR", domain: "BY", language: "RU" },
  { country: "Belgium", countryCode: "BEL", domain: "BE", language: "FR" },
  { country: "Belize", countryCode: "BLZ", domain: "BZ", language: "EN" },
  { country: "Benin", countryCode: "BEN", domain: "BJ", language: "FR" },
  { country: "Bhutan", countryCode: "BTN", domain: "BT", language: "EN" },
  {
    country: "Bolivia",
    countryCode: "BOL",
    domain: "BO",
    language: "ES",
  },
  {
    country: "Bosnia and Herzegovina",
    countryCode: "BIH",
    domain: "BA",
    language: "EN",
  },
  { country: "Botswana", countryCode: "BOT", domain: "BW", language: "EN" },
  { country: "Brazil", countryCode: "B", domain: "BR", language: "EN" },
  {
    country: "Brunei Darussalam",
    countryCode: "BRU",
    domain: "BN",
    language: "EN",
  },
  { country: "Bulgaria", countryCode: "BUL", domain: "BG", language: "EN" },
  { country: "Burkina Faso", countryCode: "BFA", domain: "BF", language: "FR" },
  { country: "Burundi", countryCode: "BDI", domain: "BI", language: "FR" },
  { country: "Cabo Verde", countryCode: "CPV", domain: "CV", language: "FR" },
  { country: "Cambodia", countryCode: "CBG", domain: "KH", language: "EN" },
  { country: "Cameroon", countryCode: "CME", domain: "CM", language: "FR" },
  { country: "Canada", countryCode: "CAN", domain: "CA", language: "EN" },
  {
    country: "Central African Republic",
    countryCode: "CAF",
    domain: "CF",
    language: "FR",
  },
  { country: "Chad", countryCode: "TCD", domain: "TD", language: "FR" },
  { country: "Chile", countryCode: "CHL", domain: "CL", language: "ES" },
  { country: "China", countryCode: "CHN", domain: "CN", language: "CN" },
  { country: "Colombia", countryCode: "CLM", domain: "CO", language: "ES" },
  { country: "Comoros", countryCode: "COM", domain: "KM", language: "FR" },
  {
    country: "Congo",
    countryCode: "COG",
    domain: "CG",
    language: "FR",
  },
  { country: "Costa Rica", countryCode: "CTR", domain: "CR", language: "ES" },
  {
    country: "Côte d'Ivoire",
    countryCode: "CTI",
    domain: "CI",
    language: "FR",
  },
  { country: "Croatia", countryCode: "HRV", domain: "HR", language: "EN" },
  { country: "Cuba", countryCode: "CUB", domain: "CU", language: "ES" },
  { country: "Cyprus", countryCode: "CYP", domain: "CY", language: "EN" },
  {
    country: "Czech Republic",
    countryCode: "CZE",
    domain: "CZ",
    language: "EN",
  },
  {
    country: "DPR Korea",
    countryCode: "KRE",
    domain: "KP",
    language: "EN",
  },
  {
    country: "DR Congo",
    countryCode: "COD",
    domain: "CD",
    language: "FR",
  },
  { country: "Denmark", countryCode: "DNK", domain: "DK", language: "EN" },
  { country: "Djibouti", countryCode: "DJI", domain: "DJ", language: "AR" },
  { country: "Dominica", countryCode: "DMA", domain: "DM", language: "EN" },
  {
    country: "Dominican Republic",
    countryCode: "DOM",
    domain: "DO",
    language: "ES",
  },
  { country: "Ecuador", countryCode: "EQA", domain: "EC", language: "ES" },
  { country: "Egypt", countryCode: "EGY", domain: "EG", language: "AR" },
  { country: "El Salvador", countryCode: "SLV", domain: "SV", language: "ES" },
  {
    country: "Equatorial Guinea",
    countryCode: "GNE",
    domain: "GQ",
    language: "ES",
  },
  { country: "Eritrea", countryCode: "ERI", domain: "ER", language: "EN" },
  { country: "Estonia", countryCode: "EST", domain: "EE", language: "EN" },
  { country: "Eswatini", countryCode: "SWZ", domain: "SZ", language: "EN" },
  { country: "Ethiopia", countryCode: "ETH", domain: "ET", language: "EN" },
  { country: "Fiji", countryCode: "FJI", domain: "FJ", language: "EN" },
  { country: "Finland", countryCode: "FIN", domain: "FI", language: "EN" },
  { country: "France", countryCode: "F", domain: "FR", language: "FR" },
  { country: "Gabon", countryCode: "GAB", domain: "GA", language: "FR" },
  { country: "Gambia", countryCode: "GMB", domain: "GM", language: "EN" },
  { country: "Georgia", countryCode: "GEO", domain: "GE", language: "EN" },
  { country: "Germany", countryCode: "D", domain: "DE", language: "EN" },
  { country: "Ghana", countryCode: "GHA", domain: "GH", language: "EN" },
  { country: "Greece", countryCode: "GRC", domain: "GR", language: "EN" },
  { country: "Grenada", countryCode: "GRD", domain: "GD", language: "EN" },
  { country: "Guatemala", countryCode: "GTM", domain: "GT", language: "ES" },
  { country: "Guinea", countryCode: "GUI", domain: "GN", language: "FR" },
  {
    country: "Guinea-Bissau",
    countryCode: "GNB",
    domain: "GW",
    language: "FR",
  },
  { country: "Guyana", countryCode: "GUY", domain: "GY", language: "EN" },
  { country: "Haiti", countryCode: "HTI", domain: "HT", language: "FR" },
  { country: "Honduras", countryCode: "HND", domain: "HN", language: "ES" },
  { country: "Hungary", countryCode: "HNG", domain: "HU", language: "EN" },
  { country: "Iceland", countryCode: "ISL", domain: "IS", language: "EN" },
  { country: "India", countryCode: "IND", domain: "IN", language: "EN" },
  { country: "Indonesia", countryCode: "INS", domain: "ID", language: "EN" },
  { country: "Iran", countryCode: "IRN", domain: "IR", language: "EN" },
  { country: "Iraq", countryCode: "IRQ", domain: "IQ", language: "AR" },
  { country: "Ireland", countryCode: "IRL", domain: "IE", language: "EN" },
  { country: "Israel", countryCode: "ISR", domain: "IL", language: "EN" },
  { country: "Italy", countryCode: "I", domain: "IT", language: "EN" },
  { country: "Jamaica", countryCode: "JMC", domain: "JM", language: "EN" },
  { country: "Japan", countryCode: "J", domain: "JP", language: "EN" },
  { country: "Jordan", countryCode: "JOR", domain: "JO", language: "AR" },
  { country: "Kazakhstan", countryCode: "KAZ", domain: "KZ", language: "RU" },
  { country: "Kenya", countryCode: "KEN", domain: "KE", language: "EN" },
  { country: "Kiribati", countryCode: "KIR", domain: "KI", language: "EN" },
  { country: "Korea", countryCode: "KOR", domain: "KR", language: "EN" },
  { country: "Kuwait", countryCode: "KWT", domain: "KW", language: "AR" },
  { country: "Kyrgyzstan", countryCode: "KGZ", domain: "KG", language: "RU" },
  { country: "Lao P.D.R.", countryCode: "LAO", domain: "LA", language: "EN" },
  { country: "Latvia", countryCode: "LVA", domain: "LV", language: "EN" },
  { country: "Lebanon", countryCode: "LBN", domain: "LB", language: "AR" },
  { country: "Lesotho", countryCode: "LSO", domain: "LS", language: "EN" },
  { country: "Liberia", countryCode: "LBR", domain: "LR", language: "EN" },
  { country: "Libya", countryCode: "LBY", domain: "LY", language: "AR" },
  {
    country: "Liechtenstein",
    countryCode: "LIE",
    domain: "LI",
    language: "EN",
  },
  { country: "Lithuania", countryCode: "LTU", domain: "LT", language: "EN" },
  { country: "Luxembourg", countryCode: "LUX", domain: "LU", language: "FR" },
  { country: "Madagascar", countryCode: "MDG", domain: "MG", language: "FR" },
  { country: "Malawi", countryCode: "MWI", domain: "MW", language: "EN" },
  { country: "Malaysia", countryCode: "MLA", domain: "MY", language: "EN" },
  { country: "Maldives", countryCode: "MLD", domain: "MV", language: "EN" },
  { country: "Mali", countryCode: "MLI", domain: "ML", language: "FR" },
  { country: "Malta", countryCode: "MLT", domain: "MT", language: "EN" },
  {
    country: "Marshall Islands",
    countryCode: "MHL",
    domain: "MH",
    language: "EN",
  },
  { country: "Mauritania", countryCode: "MTN", domain: "MR", language: "AR" },
  { country: "Mauritius", countryCode: "MAU", domain: "MU", language: "EN" },
  { country: "Mexico", countryCode: "MEX", domain: "MX", language: "ES" },
  { country: "Micronesia", countryCode: "FSM", domain: "FM", language: "EN" },
  { country: "Moldova", countryCode: "MDA", domain: "MD", language: "RU" },
  { country: "Monaco", countryCode: "MCO", domain: "MC", language: "FR" },
  { country: "Mongolia", countryCode: "MNG", domain: "MN", language: "EN" },
  { country: "Montenegro", countryCode: "MNE", domain: "ME", language: "EN" },
  { country: "Morocco", countryCode: "MRC", domain: "MA", language: "AR" },
  { country: "Mozambique", countryCode: "MOZ", domain: "MZ", language: "EN" },
  { country: "Myanmar", countryCode: "BRM", domain: "MM", language: "EN" },
  { country: "Namibia", countryCode: "NMB", domain: "NA", language: "EN" },
  { country: "Nauru", countryCode: "NRU", domain: "NR", language: "EN" },
  { country: "Nepal", countryCode: "NPL", domain: "NP", language: "EN" },
  { country: "Netherlands", countryCode: "HOL", domain: "NL", language: "EN" },
  { country: "New Zealand", countryCode: "NZL", domain: "NZ", language: "EN" },
  { country: "Nicaragua", countryCode: "NCG", domain: "NI", language: "ES" },
  { country: "Niger", countryCode: "NGR", domain: "NE", language: "FR" },
  { country: "Nigeria", countryCode: "NIG", domain: "NG", language: "EN" },
  {
    country: "North Macedonia",
    countryCode: "MKD",
    domain: "MK",
    language: "EN",
  },
  { country: "Norway", countryCode: "NOR", domain: "NO", language: "EN" },
  { country: "Oman", countryCode: "OMA", domain: "OM", language: "AR" },
  { country: "Pakistan", countryCode: "PAK", domain: "PK", language: "EN" },
  { country: "Panama", countryCode: "PNR", domain: "PA", language: "ES" },
  {
    country: "Papua New Guinea",
    countryCode: "PNG",
    domain: "PG",
    language: "EN",
  },
  { country: "Paraguay", countryCode: "PRG", domain: "PY", language: "ES" },
  { country: "Peru", countryCode: "PRU", domain: "PE", language: "ES" },
  { country: "Philippines", countryCode: "PHL", domain: "PH", language: "EN" },
  { country: "Poland", countryCode: "POL", domain: "PL", language: "EN" },
  { country: "Portugal", countryCode: "POR", domain: "PT", language: "EN" },
  { country: "Qatar", countryCode: "QAT", domain: "QA", language: "AR" },
  { country: "Romania", countryCode: "ROU", domain: "RO", language: "EN" },
  {
    country: "Russian Federation",
    countryCode: "RUS",
    domain: "RU",
    language: "RU",
  },
  { country: "Rwanda", countryCode: "RRW", domain: "RW", language: "EN" },
  {
    country: "Saint Kitts and Nevis",
    countryCode: "KNA",
    domain: "KN",
    language: "EN",
  },
  { country: "Saint Lucia", countryCode: "LCA", domain: "LC", language: "EN" },
  {
    country: "Saint Vincent and the Grenadines",
    countryCode: "VCT",
    domain: "VC",
    language: "EN",
  },
  { country: "Samoa", countryCode: "SMO", domain: "WS", language: "EN" },
  { country: "San Marino", countryCode: "SMR", domain: "SM", language: "EN" },
  {
    country: "Sao Tome and Principe",
    countryCode: "STP",
    domain: "ST",
    language: "FR",
  },
  { country: "Saudi Arabia", countryCode: "ARS", domain: "SA", language: "AR" },
  { country: "Senegal", countryCode: "SEN", domain: "SN", language: "FR" },
  { country: "Serbia", countryCode: "SRB", domain: "RS", language: "EN" },
  { country: "Seychelles", countryCode: "SEY", domain: "SC", language: "EN" },
  { country: "Sierra Leone", countryCode: "SRL", domain: "SL", language: "EN" },
  { country: "Singapore", countryCode: "SNG", domain: "SG", language: "EN" },
  { country: "Slovakia", countryCode: "SVK", domain: "SK", language: "EN" },
  { country: "Slovenia", countryCode: "SVN", domain: "SI", language: "EN" },
  {
    country: "Solomon Islands",
    countryCode: "SLM",
    domain: "SB",
    language: "EN",
  },
  { country: "Somalia", countryCode: "SOM", domain: "SO", language: "AR" },
  { country: "South Africa", countryCode: "AFS", domain: "ZA", language: "EN" },
  { country: "South Sudan", countryCode: "SSD", domain: "SS", language: "EN" },
  { country: "Spain", countryCode: "E", domain: "ES", language: "ES" },
  { country: "Sri Lanka", countryCode: "CLN", domain: "LK", language: "EN" },
  { country: "Sudan", countryCode: "SDN", domain: "SD", language: "AR" },
  { country: "Suriname", countryCode: "SUR", domain: "SR", language: "EN" },
  { country: "Sweden", countryCode: "S", domain: "SE", language: "EN" },
  { country: "Switzerland", countryCode: "SUI", domain: "CH", language: "FR" },
  {
    country: "Syrian Arab Republic",
    countryCode: "SYR",
    domain: "SY",
    language: "AR",
  },
  { country: "Tajikistan", countryCode: "TJK", domain: "TJ", language: "RU" },
  { country: "Tanzania", countryCode: "TZA", domain: "TZ", language: "EN" },
  { country: "Thailand", countryCode: "THA", domain: "TH", language: "EN" },
  { country: "Timor-Leste", countryCode: "TLS", domain: "TL", language: "EN" },
  { country: "Togo", countryCode: "TGO", domain: "TG", language: "FR" },
  { country: "Tonga", countryCode: "TON", domain: "TO", language: "EN" },
  {
    country: "Trinidad and Tobago",
    countryCode: "TRD",
    domain: "TT",
    language: "EN",
  },
  { country: "Tunisia", countryCode: "TUN", domain: "TN", language: "AR" },
  { country: "Turkmenistan", countryCode: "TKM", domain: "TM", language: "RU" },
  { country: "Tuvalu", countryCode: "TUV", domain: "TV", language: "EN" },
  { country: "Türkiye", countryCode: "TUR", domain: "TR", language: "EN" },
  { country: "Uganda", countryCode: "UGA", domain: "UG", language: "EN" },
  { country: "Ukraine", countryCode: "UKR", domain: "UA", language: "RU" },
  {
    country: "United Arab Emirates",
    countryCode: "UAE",
    domain: "AE",
    language: "AR",
  },
  { country: "United Kingdom", countryCode: "G", domain: "GB", language: "EN" },
  {
    country: "United States",
    countryCode: "USA",
    domain: "US",
    language: "EN",
  },
  { country: "Uruguay", countryCode: "URG", domain: "UY", language: "ES" },
  { country: "Uzbekistan", countryCode: "UZB", domain: "UZ", language: "RU" },
  { country: "Vanuatu", countryCode: "VUT", domain: "VU", language: "EN" },
  { country: "Vatican", countryCode: "CVA", domain: "VA", language: "FR" },
  { country: "Venezuela", countryCode: "VEN", domain: "VE", language: "ES" },
  { country: "Viet Nam", countryCode: "VTN", domain: "VN", language: "EN" },
  { country: "Yemen", countryCode: "YEM", domain: "YE", language: "AR" },
  { country: "Zambia", countryCode: "ZMB", domain: "ZM", language: "EN" },
  { country: "Zimbabwe", countryCode: "ZWE", domain: "ZW", language: "EN" },
];

export const ITU_LANGUAGE_BY_DOMAIN: Record<ITUDomain, ITULanguage> = {
  AF: "EN",
  AL: "EN",
  DZ: "AR",
  AD: "FR",
  AO: "EN",
  AG: "EN",
  AR: "ES",
  AM: "EN",
  AU: "EN",
  AT: "EN",
  AZ: "RU",
  BS: "EN",
  BH: "AR",
  BD: "EN",
  BB: "EN",
  BY: "RU",
  BE: "FR",
  BZ: "EN",
  BJ: "FR",
  BT: "EN",
  BO: "ES",
  BA: "EN",
  BW: "EN",
  BR: "EN",
  BN: "EN",
  BG: "EN",
  BF: "FR",
  BI: "FR",
  CV: "FR",
  KH: "EN",
  CM: "FR",
  CA: "EN",
  CF: "FR",
  TD: "FR",
  CL: "ES",
  CN: "CN",
  CO: "ES",
  KM: "FR",
  CG: "FR",
  CR: "ES",
  CI: "FR",
  HR: "EN",
  CU: "ES",
  CY: "EN",
  CZ: "EN",
  KP: "EN",
  CD: "FR",
  DK: "EN",
  DJ: "AR",
  DM: "EN",
  DO: "ES",
  EC: "ES",
  EG: "AR",
  SV: "ES",
  GQ: "ES",
  ER: "EN",
  EE: "EN",
  SZ: "EN",
  ET: "EN",
  FJ: "EN",
  FI: "EN",
  FR: "FR",
  GA: "FR",
  GM: "EN",
  GE: "EN",
  DE: "EN",
  GH: "EN",
  GR: "EN",
  GD: "EN",
  GT: "ES",
  GN: "FR",
  GW: "FR",
  GY: "EN",
  HT: "FR",
  HN: "ES",
  HU: "EN",
  IS: "EN",
  IN: "EN",
  ID: "EN",
  IR: "EN",
  IQ: "AR",
  IE: "EN",
  IL: "EN",
  IT: "EN",
  JM: "EN",
  JP: "EN",
  JO: "AR",
  KZ: "RU",
  KE: "EN",
  KI: "EN",
  KR: "EN",
  KW: "AR",
  KG: "RU",
  LA: "EN",
  LV: "EN",
  LB: "AR",
  LS: "EN",
  LR: "EN",
  LY: "AR",
  LI: "EN",
  LT: "EN",
  LU: "FR",
  MG: "FR",
  MW: "EN",
  MY: "EN",
  MV: "EN",
  ML: "FR",
  MT: "EN",
  MH: "EN",
  MR: "AR",
  MU: "EN",
  MX: "ES",
  FM: "EN",
  MD: "RU",
  MC: "FR",
  MN: "EN",
  ME: "EN",
  MA: "AR",
  MZ: "EN",
  MM: "EN",
  NA: "EN",
  NR: "EN",
  NP: "EN",
  NL: "EN",
  NZ: "EN",
  NI: "ES",
  NE: "FR",
  NG: "EN",
  MK: "EN",
  NO: "EN",
  OM: "AR",
  PK: "EN",
  PA: "ES",
  PG: "EN",
  PY: "ES",
  PE: "ES",
  PH: "EN",
  PL: "EN",
  PT: "EN",
  QA: "AR",
  RO: "EN",
  RU: "RU",
  RW: "EN",
  KN: "EN",
  LC: "EN",
  VC: "EN",
  WS: "EN",
  SM: "EN",
  ST: "FR",
  SA: "AR",
  SN: "FR",
  RS: "EN",
  SC: "EN",
  SL: "EN",
  SG: "EN",
  SK: "EN",
  SI: "EN",
  SB: "EN",
  SO: "AR",
  ZA: "EN",
  SS: "EN",
  ES: "ES",
  LK: "EN",
  SD: "AR",
  SR: "EN",
  SE: "EN",
  CH: "FR",
  SY: "AR",
  TJ: "RU",
  TZ: "EN",
  TH: "EN",
  TL: "EN",
  TG: "FR",
  TO: "EN",
  TT: "EN",
  TN: "AR",
  TM: "RU",
  TV: "EN",
  TR: "EN",
  UG: "EN",
  UA: "RU",
  AE: "AR",
  GB: "EN",
  US: "EN",
  UY: "ES",
  UZ: "RU",
  VU: "EN",
  VA: "FR",
  VE: "ES",
  VN: "EN",
  YE: "AR",
  ZM: "EN",
  ZW: "EN",
};
