# Markdownlint Rules
# see https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md
#
# Header levels should only increment by one level at a time
# MD001: false
#
# First header should be a top level header
# MD002: false
#
# Header style
# MD003: false
#
# Unordered list style
# MD004: false
#
# Inconsistent indentation for list items at the same level
# MD005: false
#
# Consider starting bulleted lists at the beginning of the line
# MD006: false
#
# Unordered list indentation
# MD007: false
#
# Trailing spaces
# MD009: false
#
# Hard tabs
# MD010: false
#
# Reversed link syntax
# MD011: false
#
# Multiple consecutive blank lines
# MD012: false
#
# Line length
MD013: false
#
# Dollar signs used before commands without showing output
# MD014: false
#
# No space after hash on atx style header
# MD018: false
#
# Multiple spaces after hash on atx style header
# MD019: false
#
# No space inside hashes on closed atx style header
# MD020: false
#
# Multiple spaces inside hashes on closed atx style header
# MD021: false
#
# Headers should be surrounded by blank lines
# MD022: false
#
# Headers must start at the beginning of the line
# MD023: false
#
# Multiple headers with the same content
# MD024: false
#
# Multiple top level headers in the same document
# MD025: false
#
# Trailing punctuation in header
MD026: false
#
# Multiple spaces after blockquote symbol
# MD027: false
#
# Blank line inside blockquote
# MD028: false
#
# Ordered list item prefix
# MD029: false
#
# Spaces after list markers
# MD030: false
#
# Fenced code blocks should be surrounded by blank lines
# MD031: false
#
# Lists should be surrounded by blank lines
# MD032: false
#
# Inline HTML
MD033: false
#
# Bare URL used
# MD034: false
#
# Horizontal rule style
# MD035: false
#
# Emphasis used instead of a header
MD036: false
#
# Spaces inside emphasis markers
# MD037: false
#
# Spaces inside code span elements
# MD038: false
#
# Spaces inside link text
# MD039: false
#
# Fenced code blocks should have a language specified
# MD040: false
#
# First line in file should be a top level header
MD041: false
#
# Code block style
# MD046: false
#
# File should end with a single newline character
# MD047: false
