import type { ServiceIdString } from './ServiceId';
import type { SerializedCertificateType } from './schema';

export type StorageItem = {
  // areWeASubscriber: boolean;
  // attachmentMigration_isComplete: boolean;
  // attachmentMigration_lastProcessedIndex: number;
  // avatarUrl: string | undefined;
  // backupCredentials: ReadonlyArray<BackupCredentialType>;
  // backupCredentialsLastRequestTime: number;
  // backupsSubscriberCurrencyCode: string;
  // backupsSubscriberId: Uint8Array;
  // backupsSubscriptionManuallyCancelled: boolean;
  blocked: ReadonlyArray<string>;
  'blocked-groups': ReadonlyArray<string>;
  'blocked-uuids': ReadonlyArray<ServiceIdString>;
  // callLinkAuthCredentials: ReadonlyArray<GroupCredentialType>;
  // 'challenge:conversations': ReadonlyArray<RegisteredChallengeType>;
  // chromiumRegistrationDone: '';
  // chromiumRegistrationDoneEver: '';
  device_name: string;
  deviceNameEncrypted: boolean;
  // displayBadgesOnProfile: boolean;
  // donorSubscriptionManuallyCancelled: boolean;
  // groupCredentials: ReadonlyArray<GroupCredentialType>;
  // hasCompletedUsernameOnboarding: boolean;
  // hasRegisterSupportForUnauthenticatedDelivery: boolean;
  // hasSeenGroupStoryEducationSheet: boolean;
  // hasSetMyStoriesPrivacy: boolean;
  // hasStoriesDisabled: boolean;
  // hasViewedOnboardingStory: boolean;
  // identityKeyMap: IdentityKeyMap;
  // 'indexeddb-delete-needed': boolean;
  // keepMutedChatsArchived: boolean;
  // lastAttemptedToRefreshProfilesAt: number;
  // lastReceivedAtCounter: number;
  // lastResortKeyUpdateTime: number;
  // lastResortKeyUpdateTimePNI: number;
  // linkPreviews: boolean;
  // manifestVersion: number;
  // masterKey: string;
  // masterKeyLastRequestTime: number;
  // maxKyberPreKeyId: number;
  // maxKyberPreKeyIdPNI: number;
  // maxPreKeyId: number;
  // maxPreKeyIdPNI: number;
  // needOrphanedAttachmentCheck: boolean;
  // nextScheduledUpdateKeyTime: number;
  number_id: string;
  password: string;
  // paymentAddress: string;
  // phoneNumberDiscoverability: PhoneNumberDiscoverability;
  // phoneNumberSharingMode: PhoneNumberSharingMode;
  pni: string;
  // primarySendsSms: boolean;
  // profileKey: Uint8Array;
  // 'read-receipt-setting': boolean;
  // regionCode: string;
  // registrationIdMap: Record<ServiceIdString, number>;
  // remoteBuildExpiration: number;
  // remoteConfig: RemoteConfigType;
  // retryPlaceholders: ReadonlyArray<RetryItemType>;
  // sealedSenderIndicators: boolean;
  senderCertificate: SerializedCertificateType;
  // senderCertificateNoE164: SerializedCertificateType;
  // serverTimeSkew: number;
  // sessionResets: SessionResetsType;
  // setBackupSignatureKey: boolean;
  // signedKeyId: number;
  // signedKeyIdPNI: number;
  // signedKeyUpdateTime: number;
  // signedKeyUpdateTimePNI: number;
  // storageCredentials: StorageServiceCredentials;
  // storageFetchComplete: boolean;
  // storageKey: string;
  // 'storage-service-error-records': ReadonlyArray<UnknownRecord>;
  // 'storage-service-pending-deletes': ReadonlyArray<ExtendedStorageID>;
  // 'storage-service-unknown-records': ReadonlyArray<UnknownRecord>;
  // storyViewReceiptsEnabled: boolean;
  // subscriberCurrencyCode: string;
  // subscriberId: Uint8Array;
  // synced_at: number;
  // typingIndicators: boolean;
  // unidentifiedDeliveryIndicators: boolean;
  // universalExpireTimer: number;
  // unreadCount: number;
  // userAgent: string;
  // usernameCorrupted: boolean;
  // usernameLastIntegrityCheck: number;
  // usernameLink: { entropy: Uint8Array; serverId: Uint8Array; };
  // usernameLinkColor: number;
  // usernameLinkCorrupted: boolean;
  uuid_id: string;

  // *********************
  // UI Configuration
  // 'always-relay-calls': boolean;
  // 'audio-notification': boolean;
  // 'auto-download-update': boolean;
  // 'badge-count-muted-conversations': boolean;
  // 'call-ringtone-notification': boolean;
  // 'call-system-notification': boolean;
  // 'hide-menu-bar': boolean;
  // 'incoming-call-notification': boolean;
  // 'notification-draw-attention': boolean;
  // 'notification-setting': NotificationSettingType;
  // 'preferred-audio-input-device': AudioDevice;
  // 'preferred-audio-output-device': AudioDevice;
  // 'preferred-video-input-device': string;
  // 'sent-media-quality': SentMediaQualitySettingType;
  // autoConvertEmoji: boolean;
  // audioMessage: boolean;
  // customColors: CustomColorsItemType;
  // defaultConversationColor: DefaultConversationColorType;
  // existingOnboardingStoryMessageIds: ReadonlyArray<string> | undefined;
  // hasCompletedSafetyNumberOnboarding: boolean;
  // hasCompletedUsernameLinkOnboarding: boolean;
  // localDeleteWarningShown: boolean;
  // navTabsCollapsed: boolean;
  // pinnedConversationIds: ReadonlyArray<string>;
  // preferContactAvatars: boolean;
  // preferredLeftPaneWidth: number;
  // preferredReactionEmoji: ReadonlyArray<string>;
  // showStickerPickerHint: boolean;
  // showStickersIntroduction: boolean;
  // skinTone: number;
  // textFormatting: boolean;
  // version: string;
  // zoomFactor: ZoomFactorType;
};

export type StorageKey = keyof StorageItem;

export type SerializedStorageItem<K extends StorageKey> = {
  id: K;
  value: Serialized<StorageItem[K]>;
};

type Serialized<Value> = Value extends Uint8Array
  ? string
  : { [Key in keyof Value]: Serialized<Value[Key]> };

